/** Aggregierte Bewerbungs- und Job-Daten für das Carlo-CV-Dashboard. */
window.DASHBOARD_DATA = {
  bewerbungen: [
    {
      id: "denner-bern-riedbach",
      firma: "Denner AG",
      titel: "Verkäufer*in 80-100%",
      ort: "Bern, Riedbachstrasse",
      quelle: "kuratiert",
      art: "stelle",
      link: "https://jobs.migros.ch/de/unsere-unternehmen/job/denner-ag/verkauferin/edbfd2ae-125b-4db0-94e6-0ac771b810c1",
      mappe: "applications/denner-bern-riedbach/index.html",
      stand: null,
    },
    {
      id: "erupt-lounge-bern",
      firma: "ERUPT AG",
      titel: "Lounge Host / Gästebetreuung (Vollzeit)",
      ort: "Bern",
      quelle: "kuratiert",
      art: "initiativ",
      link: "https://erupt.ch/jobs",
      mappe: "applications/erupt-lounge-bern/index.html",
      stand: "2026-09-22",
    },
    {
      id: "fusion-arena-bern",
      firma: "Fusion Arena Bern GmbH",
      titel: "Gastgeber / VR Host",
      ort: "Bern",
      quelle: "kuratiert",
      art: "initiativ",
      link: "https://fusionarena.ch/bern/",
      mappe: "applications/fusion-arena-bern/index.html",
      stand: "2026-09-19",
    },
    {
      id: "mediamarkt-guemligen",
      firma: "MediaMarkt",
      titel: "Verkaufsberater*in 100% (m/w/d)",
      ort: "Gümligen",
      quelle: "kuratiert",
      art: "stelle",
      link: "https://careers.mediamarktsaturn.com/MediaMarktCH/job/Gümligen-Verkaufsberaterin-100-(mwd)-3073/1423378833/",
      mappe: "applications/mediamarkt-guemligen/index.html",
      stand: "2026-09-20",
    },
    {
      id: "sando-bern",
      firma: "Sando BBZ Sàrl",
      titel: "Chef de Partie",
      ort: "Bern, Bubenbergplatz",
      quelle: "kuratiert",
      art: "stelle",
      link: null,
      mappe: "applications/sando-bern/index.html",
      stand: "2026-09-19",
    },
    {
      id: "virtual-experience-bern",
      firma: "Virtual Experience GmbH",
      titel: "Game Master / VR Host",
      ort: "Bern",
      quelle: "kuratiert",
      art: "initiativ",
      link: "https://www.virtualexperience.ch/",
      mappe: "applications/virtual-experience-bern/index.html",
      stand: "2026-09-20",
    },
    {
      id: "automobile-nemeth-hinterkappelen",
      firma: "Automobile Nemeth AG",
      titel: "Automobil Verkäufer/in (Audi, Maserati & Occasionsfahrzeuge)",
      ort: "Hinterkappelen",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/89d5729a-0980-47b9-835d-ae1a618de604/",
      mappe: "scraper-applications/automobile-nemeth-hinterkappelen/index.html",
      stand: null,
    },
    {
      id: "volg-kandersteg",
      firma: "Volg Detailhandels AG",
      titel: "Verkäuferin, Verkäufer",
      ort: "Kandersteg",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/937a13a8-e16a-4484-8ae4-1ddaf3be7213/",
      mappe: "scraper-applications/volg-kandersteg/index.html",
      stand: null,
    },
    {
      id: "volg-reutigen",
      firma: "Volg Detailhandels AG",
      titel: "Verkäuferin / Verkäufer",
      ort: "Reutigen",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/7ee0f3fc-bcd9-4270-924f-1129fbecd97b/",
      mappe: "scraper-applications/volg-reutigen/index.html",
      stand: null,
    },
    {
      id: "landi-konolfingen",
      firma: "LANDI Aare Genossenschaft",
      titel: "Verkäufer TopShop w/m/d",
      ort: "Konolfingen",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/65ff7dce-45f8-4859-9026-264d9dc5276f/",
      mappe: "scraper-applications/landi-konolfingen/index.html",
      stand: null,
    },
    {
      id: "volg-blumenstein",
      firma: "Volg Detailhandels AG",
      titel: "Verkäuferin, Verkäufer f/h/d",
      ort: "Blumenstein",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/bf1f8048-710e-4385-8efc-7ab41fbbadc3/",
      mappe: "scraper-applications/volg-blumenstein/index.html",
      stand: null,
    },
    {
      id: "landi-spiez",
      firma: "LANDI Genossenschaften",
      titel: "Verkäuferin / Verkäufer TopShop 60-80% w/m/d",
      ort: "Spiez",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/164c839d-b365-408c-a857-666485cd11cb/",
      mappe: "scraper-applications/landi-spiez/index.html",
      stand: null,
    },
    {
      id: "landi-laupen",
      firma: "LANDI Genossenschaften",
      titel: "Verkäuferin / Verkäufer Festservice & Getränke w/m/d",
      ort: "Laupen",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/f5c27fe9-6237-4951-be7c-42510a0c9de1/",
      mappe: "scraper-applications/landi-laupen/index.html",
      stand: null,
    },
    {
      id: "meier-tobler-bern-solothurn",
      firma: "Meier Tobler AG",
      titel: "Verkäufer Heizung / Sanitär (w/m)",
      ort: "Region Bern/Solothurn",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/f4d2a7df-c529-4828-8af6-251282d2d152/",
      mappe: "scraper-applications/meier-tobler-bern-solothurn/index.html",
      stand: null,
    },
    {
      id: "salt-bern",
      firma: "Salt Mobile SA",
      titel: "Salt Store Verkäufer-/Verkäuferin Bern 100%",
      ort: "Bern",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/40598104-ff32-4510-8693-85655df32d9b/",
      mappe: "scraper-applications/salt-bern/index.html",
      stand: null,
    },
    {
      id: "rotho-blaas-bern",
      firma: "Rotho Blaas Schweiz GmbH",
      titel: "Technischer Verkäufer im Außendienst - Berner Oberland",
      ort: "Bern / Berner Oberland",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/b85faeae-3adc-4815-85c5-c5a35406287f/",
      mappe: "scraper-applications/rotho-blaas-bern/index.html",
      stand: null,
    },
    {
      id: "magic-x-bern",
      firma: "Magic X Retail AG",
      titel: "Verkäufer/in 20-60% (m/w/d) für Bern im Stundenlohn",
      ort: "Bern",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/cd6dfd5d-5314-4405-b7ca-fe74eb18969e/",
      mappe: "scraper-applications/magic-x-bern/index.html",
      stand: null,
    },
    {
      id: "salt-bienne",
      firma: "Salt Mobile SA",
      titel: "Salt Store Verkäufer/in Bienne/Biel 80%-100%",
      ort: "Biel/Bienne",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/05e7794b-a12a-4bd8-9490-826e7ac5fada/",
      mappe: "scraper-applications/salt-bienne/index.html",
      stand: null,
    },
    {
      id: "magic-x-lyssach",
      firma: "Magic X Retail AG",
      titel: "Verkäufer/in 30-40% (m/w/d) für Lyssach im Stundenlohn",
      ort: "Lyssach",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/9c92ca33-fa16-45f0-8ff0-08942bfff6cb/",
      mappe: "scraper-applications/magic-x-lyssach/index.html",
      stand: null,
    },
    {
      id: "meier-tobler-thun",
      firma: "Meier Tobler AG",
      titel: "Leiter Marché | Verkäufer Heizung / Sanitär (w/m)",
      ort: "Thun",
      quelle: "scraper",
      art: "stelle",
      link: "https://www.jobs.ch/de/stellenangebote/detail/7e4ad1c5-e0d9-44c6-bb0a-2d497dc8b519/",
      mappe: "scraper-applications/meier-tobler-thun/index.html",
      stand: null,
    },
  ],

  jobs: [
    {
      id: "job-automobile-nemeth",
      titel: "Automobil Verkäufer/in (Audi, Maserati & exklusive Occasionsfahrzeuge)",
      firma: "Automobile Nemeth AG",
      ort: "Hinterkappelen",
      veroeffentlicht: "Vor 3 Wochen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/89d5729a-0980-47b9-835d-ae1a618de604/",
      bewerbungId: "automobile-nemeth-hinterkappelen",
    },
    {
      id: "job-volg-kandersteg",
      titel: "Verkäuferin, Verkäufer",
      firma: "Volg Detailhandels AG",
      ort: "Kandersteg",
      veroeffentlicht: "Vor 6 Tagen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/937a13a8-e16a-4484-8ae4-1ddaf3be7213/",
      bewerbungId: "volg-kandersteg",
    },
    {
      id: "job-volg-reutigen",
      titel: "Verkäuferin / Verkäufer",
      firma: "Volg Detailhandels AG",
      ort: "Reutigen",
      veroeffentlicht: "Vor 4 Tagen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/7ee0f3fc-bcd9-4270-924f-1129fbecd97b/",
      bewerbungId: "volg-reutigen",
    },
    {
      id: "job-landi-konolfingen",
      titel: "Verkäufer TopShop w/m/d",
      firma: "LANDI Aare Genossenschaft",
      ort: "Konolfingen",
      veroeffentlicht: "Vor 3 Wochen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/65ff7dce-45f8-4859-9026-264d9dc5276f/",
      bewerbungId: "landi-konolfingen",
    },
    {
      id: "job-volg-blumenstein",
      titel: "Verkäuferin, Verkäufer f/h/d",
      firma: "Volg Detailhandels AG",
      ort: "Blumenstein",
      veroeffentlicht: "Vor 4 Tagen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/bf1f8048-710e-4385-8efc-7ab41fbbadc3/",
      bewerbungId: "volg-blumenstein",
    },
    {
      id: "job-landi-spiez",
      titel: "Verkäuferin / Verkäufer TopShop 60-80% w/m/d",
      firma: "LANDI Genossenschaften",
      ort: "Spiez",
      veroeffentlicht: "Letzte Woche",
      link: "https://www.jobs.ch/de/stellenangebote/detail/164c839d-b365-408c-a857-666485cd11cb/",
      bewerbungId: "landi-spiez",
    },
    {
      id: "job-landi-laupen",
      titel: "Verkäuferin / Verkäufer Festservice & Getränke w/m/d",
      firma: "LANDI Genossenschaften",
      ort: "Laupen",
      veroeffentlicht: "Gestern",
      link: "https://www.jobs.ch/de/stellenangebote/detail/f5c27fe9-6237-4951-be7c-42510a0c9de1/",
      bewerbungId: "landi-laupen",
    },
    {
      id: "job-meier-tobler-bern",
      titel: "Verkäufer Heizung / Sanitär (w/m)",
      firma: "Meier Tobler AG",
      ort: "Region Bern/Solothurn",
      veroeffentlicht: "Vor 5 Tagen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/f4d2a7df-c529-4828-8af6-251282d2d152/",
      bewerbungId: "meier-tobler-bern-solothurn",
    },
    {
      id: "job-salt-bern",
      titel: "Salt Store Verkäufer-/Verkäuferin Bern 100%",
      firma: "Salt Mobile SA",
      ort: "Bern, Fribourg, Solothurn",
      veroeffentlicht: "Vor 2 Wochen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/40598104-ff32-4510-8693-85655df32d9b/",
      bewerbungId: "salt-bern",
    },
    {
      id: "job-rotho-blaas",
      titel: "Technischer Verkäufer im Außendienst - Berner Oberland",
      firma: "Rotho Blaas Schweiz GmbH",
      ort: "Bern",
      veroeffentlicht: "Letzte Woche",
      link: "https://www.jobs.ch/de/stellenangebote/detail/b85faeae-3adc-4815-85c5-c5a35406287f/",
      bewerbungId: "rotho-blaas-bern",
    },
    {
      id: "job-magic-x-bern",
      titel: "Verkäufer/in 20-60% (m/w/d) für Bern im Stundenlohn",
      firma: "Magic X Retail AG",
      ort: "Bern",
      veroeffentlicht: "Gestern",
      link: "https://www.jobs.ch/de/stellenangebote/detail/cd6dfd5d-5314-4405-b7ca-fe74eb18969e/",
      bewerbungId: "magic-x-bern",
    },
    {
      id: "job-salt-bienne-1",
      titel: "Salt Store Vendeur/se - Verkäufer/in Bienne/Biel 80%-100%",
      firma: "Salt Mobile SA",
      ort: "Bienne",
      veroeffentlicht: "Vor 3 Tagen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/05e7794b-a12a-4bd8-9490-826e7ac5fada/",
      bewerbungId: "salt-bienne",
    },
    {
      id: "job-salt-bienne-2",
      titel: "Salt Store Vendeur/se - Verkäufer/in Bienne/Biel 80%-100%",
      firma: "Salt Mobile SA",
      ort: "Bienne",
      veroeffentlicht: "Vor 2 Wochen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/2f44f267-1712-4bb7-bd1b-0f770bd28817/",
      bewerbungId: "salt-bienne",
    },
    {
      id: "job-magic-x-lyssach",
      titel: "Verkäufer/in 30-40% (m/w/d) für Lyssach im Stundenlohn",
      firma: "Magic X Retail AG",
      ort: "Lyssach",
      veroeffentlicht: "Vor 4 Wochen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/9c92ca33-fa16-45f0-8ff0-08942bfff6cb/",
      bewerbungId: "magic-x-lyssach",
    },
    {
      id: "job-meier-tobler-thun",
      titel: "Leiter Marché | Verkäufer Heizung / Sanitär (w/m)",
      firma: "Meier Tobler AG",
      ort: "Thun",
      veroeffentlicht: "Vor 5 Tagen",
      link: "https://www.jobs.ch/de/stellenangebote/detail/7e4ad1c5-e0d9-44c6-bb0a-2d497dc8b519/",
      bewerbungId: "meier-tobler-thun",
    },
  ],
};
